CREATE DATABASE IF NOT EXISTS BLOG;

USE BLOG;

CREATE TABLE ARTICLES(
    ARTICLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_TITLE VARCHAR(30) NOT NULL,
    ARTICLE_CONTENT TEXT NOT NULL,
    PUBLISH_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DELIMITER $$

CREATE PROCEDURE GetArticles()
BEGIN
  SELECT * FROM ARTICLES;
END$$

DELIMITER ;

INSERT INTO ARTICLES(ARTICLE_TITLE, ARTICLE_CONTENT)
VALUES('Um breve artigo', 'Este é um artigo usado para teste de desenvolvimento');

INSERT INTO ARTICLES(ARTICLE_TITLE, ARTICLE_CONTENT)
VALUES('Mais um teste', 'Como dito, essa escritura é apenas uma ferramenta de apoio');
