CREATE DATABASE BLOG;

USE BLOG;

CREATE TABLE AUTHORS(
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(255) NOT NULL,
    AUTHOR_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    AUTHOR_DESCRIPTION TEXT,
    SIGNIN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ARTICLES(
    ARTICLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_TITLE VARCHAR(30) NOT NULL,
    ARTICLE_CONTENT TEXT NOT NULL,
    PUBLISH_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AUTHOR_ID INT NOT NULL,
    FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT 
);

DELIMITER $

CREATE PROCEDURE GetAuthors()
BEGIN
SELECT * FROM AUTHORS;
END
$

CREATE PROCEDURE GetArticles()
BEGIN
SELECT * FROM ARTICLES;
END
$

DELIMITER ;

INSERT INTO AUTHORS(AUTHOR_NAME, AUTHOR_EMAIL, AUTHOR_DESCRIPTION) 
VALUES('André', 'andrelucascrvg@gmail.com', 'Estudante da UFCA');

INSERT INTO ARTICLES(ARTICLE_TITLE, ARTICLE_CONTENT, AUTHOR_ID)
VALUES('Um breve artigo', 'Este é um artigo usado para teste de desenvolvimento', 1);

INSERT INTO ARTICLES(ARTICLE_TITLE, ARTICLE_CONTENT, AUTHOR_ID)
VALUES('Mais um teste', 'Como dito, essa escritura é apenas uma ferramenta de apoio', 1);
